export { supabase } from './client'
export * from './queries'
export * from './auth'
export { apiGet, apiPost, apiPatch, apiDelete } from './lib/backend-client'
export type { Database } from './database.types'
